on: [push]

jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
    - name: rename
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export STUFF="$GITHUB_TOKEN" && echo $STUFF
    - name: print
      run: |
        set
    - name: curl
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -X PUT https://api.github.com/repos/mtttcgcg/4/branches/master/protection -H 'accept: application/vnd.github.luke-cage-preview+json' -H 'authorization: Bearer $GITHUB_TOKEN' -H 'cache-control: no-cache' -d '{ "required_status_checks": null, "enforce_admins": true, "required_pull_request_reviews": null, "restrictions": null }'
